- name: blockinfile module 
  hosts: SAMPLE 
  tasks:
    - blockinfile:
        path: /tmp/context.xml
        insertbefore: '</Context>'
        content: |
          <Resource name="jdbc/TestDB" auth="Container" type="javax.sql.DataSource"
               maxActive="50" maxIdle="30" maxWait="10000"
               username="student" password="student@1"
               driverClassName="com.mysql.jdbc.Driver"
               url="jdbc:mysql://10.142.0.7:3306/studentapp"/>
